### ISSUE TITLE
Hack together a rudimentary visualization system for NEWT-Multi

### ISSUE THREAD

**Issue by 4kbt** [4kbt/PointGravity#22]
It is very difficult to ensure that models are representative of reality without a visualization system. 

We could : 
1.  Explore for pythonic visualization tools

or

2. Continue to build NEWT-Multi / NEWT-PointGravity integration so that DisplayPoints might be able to provide a passable rendering of NEWT-Multi constructions

**Comment by eshaw** [comment]
Yeah, I've looked at this extensively. The best thing I've found to
visualize is blender. I've built up some visualizations, but it will take a
lot of work to make something that is fully functional.

чт, 13 авг. 2020 г., 3:04 PM Charlie Hagedorn <notifications@github.com>:

**Comment by 4kbt** [comment]
How well does M2CAD work under gfortran? Is that a viable visualization candidate?

**Comment by eshaw** [comment]
I feel like it should be about as good as AutoCAD 2002. I'm not sure what
the specific gripes are.

чт, 13 авг. 2020 г., 4:18 PM Charlie Hagedorn <notifications@github.com>:

**Comment by JGLee6** [comment]
There is also FreeCAD which allows for Python scripting. That could push this in a more open-source direction.

**Comment by eshaw** [comment]
Yeah, FreeCAD could work better than blender*. *I found it hard to get off
the ground, but maybe it would end up being less work to implement all the
shapes.

**Comment by JGLee6** [comment]
@eshaw seems to have worked this out with CadQuery (caedc9671dc98dac10b72fdfe555ea40b79f28bb)
