### ISSUE TITLE
annulus can yield zero moments instead of an error

### ISSUE THREAD

**Issue by 4kbt** [4kbt/PointGravity#23]
qlm.annulus(2,2,2,0,2,4,4) 

returns 

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]]

I believe that the final 4,4 should yield an error, as it is an annulus centered at 4 radians that spans \pm 4 radians, which is unphysical.

**Comment by JGLee6** [comment]
This is a good point. Many of the moments for various shapes can receive un-physical values and perform some checks but just return the empty array. We'll have to go through and see which ones have these possible inputs, but a better method would be:
`Raise ValueError('Unphysical input parameter)`
